update

diff --git a/bush/compile_c b/bush/compile_c
--- a/bush/compile_c
+++ b/bush/compile_c
@@ -6,31 +6,62 @@
 for file in ${cfiles}  ; do echo ${file} >> c_tmp; done
 
 if [ -f c_tmp ] ; then
-for file in $(cat c_tmp) ; do
-  oname=`basename ${file}`
-  oname=`echo ${oname} | sed -e 's:\.c::g'`
 
-  if [ "${build_diro}" = "yes" ] ; then
-    dname=`dirname ${file}`
-    diro=`basename ${dname}`
-    /bin/mkdir -p "${build_path}/${diro}"
-    obj="${build_path}/${diro}/${oname}.o"
-  else
-    obj="${build_path}/${oname}.o"
-  fi
+parallel_found=yes
+${bush_home}/check_app parallel
+use_status=$?;if [ ${use_status} != 0 ] ; then parallel_found=no;fi
 
-  if [ ${build_do_compile} = "yes" ] ; then
-    if [ ${build_verbose} = yes ] ; then
-      echo "bush/compile_c : do ${file} ..."
-      if [ -f ${obj} ] ; then
-        echo "bush/compile_c : WARNING : ${obj} already exists."
-      fi
-    fi
-    eval ${cc_compiler} -c ${ccflags} -o ${obj} ${file}
-    use_status=$?;if [ ${use_status} != 0 ] ; then exit ${use_status};fi
+if [ ${build_parallel} = yes -a ${parallel_found} = no ] ; then
+  echo 'bush/compile_c : -parallel but parallel not found. Continue without it.'
+fi
+
+if [ ${build_parallel} = yes -a ${parallel_found} = yes ] ; then
+
+  if [ ${build_verbose} = yes ] ; then
+    echo 'bush/compile_c : use parallel.'
   fi
-  objs="${objs} ${obj}"
-done
+  
+cat <<END > ./tmp_compile_one_c
+#!/bin/sh -f
+file=\$1
+build_o_ext=.parallel
+bush_home="${bush_home}"
+build_verbose="${build_verbose}"
+build_archive_headers="${archive_headers}"
+build_diro="${build_diro}"
+build_path="${build_path}"
+build_do_compile="${build_do_compile}"
+cc_compiler="${cc_compiler}"
+ccflags="${ccflags}"
+. ${bush_home}/compile_one_c
+END
+
+  chmod a+x ./tmp_compile_one_c
+  
+  ${bush_home}/find_rm ${build_path} '*.o.parallel'
+
+  parallel -a c_tmp './tmp_compile_one_c {}'
+
+  /bin/rm -f ./tmp_objs
+  find ${build_path} -name '*.o.parallel' -print >> ./tmp_objs
+
+  for item in $(cat ./tmp_objs) ; do
+    obj="`echo ${item} | sed -e 's:.parallel::g'`"
+    /bin/mv ${item} ${obj}
+    objs="${objs} ${obj}"
+  done
+
+  /bin/rm -f ./tmp_objs ./tmp_compile_one_c
+
+else
+
+  for file in $(cat c_tmp) ; do
+    . ${bush_home}/compile_one_c
+  done
+
+fi
+
 /bin/rm -f c_tmp
+
 fi
 
